--- 
name: Spring 2.5.6 Binary
platform_id: all
package_id: spring
platform_version: all
distribution_type: bin
distribution_file_uuid_string: openlogic-spring-2.5.6-all-bin-1
platform_vendor: all
version_visibility: public
distribution_flavor: ""
platform_arch: all
distribution_file_uuid: c453ce780d5ed57e8c98bcd086169850fc6cae1e6c0593c955b0471acfca3aed
distribution_raw_file: spring-framework-2.5.6-with-dependencies.zip
release_date: "2008-11-06"
description: Spring 2.5.6 Binary
distribution_version: 1
package_version: 2.5.6
distribution_notes: ""
